runtime: custom
env: flex
cloud_build_timeout: 1800s

resources:
  cpu: 1
  memory_gb: 1.7
  disk_size_gb: 10

manual_scaling:
  instances: 1

liveness_check:
  path: "/actuator/health"
  initial_delay_sec: 300

readiness_check:
  path: "/actuator/health"
  app_start_timeout_sec: 300
