/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ch.uzh.ifi.hase.soprafs26.controller;

import ch.uzh.ifi.hase.soprafs26.rest.dto.UserPostDTO;
import ch.uzh.ifi.hase.soprafs26.rest.dto.UserTokenDTO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-03-23T14:36:59.836313+01:00[Europe/Zurich]", comments = "Generator version: 7.7.0")
@Validated
@Tag(name = "Auth", description = "Registration and login")
public interface AuthApi {


    /**
     * POST /auth/login : Login with username and password
     *
     * @param userPostDTO (required)
     * @return Login successful; token returned (status code 200)
     * or Invalid credentials (status code 401)
     * or User not found (status code 404)
     */
    @Operation(
            operationId = "authLoginPost",
            summary = "Login with username and password",
            tags = {"Auth"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "Login successful; token returned", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = UserTokenDTO.class))
                    }),
                    @ApiResponse(responseCode = "401", description = "Invalid credentials"),
                    @ApiResponse(responseCode = "404", description = "User not found")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/auth/login",
            produces = {"application/json"},
            consumes = {"application/json"}
    )

    default ResponseEntity<UserTokenDTO> authLoginPost(
            @Parameter(name = "UserPostDTO", description = "", required = true) @Valid @RequestBody UserPostDTO userPostDTO
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    /**
     * POST /auth/logout : Logout (invalidates token, sets status OFFLINE)
     *
     * @return Logged out successfully (status code 204)
     * or Unauthorized (status code 401)
     */
    @Operation(
            operationId = "authLogoutPost",
            summary = "Logout (invalidates token, sets status OFFLINE)",
            tags = {"Auth"},
            responses = {
                    @ApiResponse(responseCode = "204", description = "Logged out successfully"),
                    @ApiResponse(responseCode = "401", description = "Unauthorized")
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/auth/logout"
    )

    default ResponseEntity<Void> authLogoutPost(

    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /users : Register a new user (S1)
     *
     * @param userPostDTO (required)
     * @return User created; token returned (status code 201)
     * or Username already taken (status code 409)
     */
    @Operation(
            operationId = "usersPost",
            summary = "Register a new user (S1)",
            tags = {"Auth"},
            responses = {
                    @ApiResponse(responseCode = "201", description = "User created; token returned", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = UserTokenDTO.class))
                    }),
                    @ApiResponse(responseCode = "409", description = "Username already taken")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/users",
            produces = {"application/json"},
            consumes = {"application/json"}
    )

    default ResponseEntity<UserTokenDTO> usersPost(
            @Parameter(name = "UserPostDTO", description = "", required = true) @Valid @RequestBody UserPostDTO userPostDTO
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
