/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ch.uzh.ifi.hase.soprafs26.controller;

import ch.uzh.ifi.hase.soprafs26.rest.dto.ReactionPostDTO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-03-23T14:36:59.836313+01:00[Europe/Zurich]", comments = "Generator version: 7.7.0")
@Validated
@Tag(name = "Reactions", description = "Live emoji reactions")
public interface ReactionsApi {

    /**
     * POST /sessions/{sessionId}/reactions : Send a live reaction during a performance (S9)
     *
     * @param sessionId       (required)
     * @param reactionPostDTO (required)
     * @return Reaction sent (status code 201)
     * or No song currently performing (status code 400)
     * or Session not found (status code 404)
     */
    @Operation(
            operationId = "sessionsSessionIdReactionsPost",
            summary = "Send a live reaction during a performance (S9)",
            tags = {"Reactions"},
            responses = {
                    @ApiResponse(responseCode = "201", description = "Reaction sent"),
                    @ApiResponse(responseCode = "400", description = "No song currently performing"),
                    @ApiResponse(responseCode = "404", description = "Session not found")
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/sessions/{sessionId}/reactions",
            consumes = {"application/json"}
    )

    default ResponseEntity<Void> sessionsSessionIdReactionsPost(
            @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") Long sessionId,
            @Parameter(name = "ReactionPostDTO", description = "", required = true) @Valid @RequestBody ReactionPostDTO reactionPostDTO
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
