/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ch.uzh.ifi.hase.soprafs26.controller;

import ch.uzh.ifi.hase.soprafs26.rest.dto.*;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-03-23T14:36:59.836313+01:00[Europe/Zurich]", comments = "Generator version: 7.7.0")
@Validated
@Tag(name = "Sessions", description = "Karaoke session lifecycle")
public interface SessionsApi {


    /**
     * POST /sessions : Create a new karaoke session (S3)
     *
     * @param sessionPostDTO (required)
     * @return Session created; creator becomes admin (status code 201)
     * or Unauthorized (status code 401)
     */
    @Operation(
            operationId = "sessionsPost",
            summary = "Create a new karaoke session (S3)",
            tags = {"Sessions"},
            responses = {
                    @ApiResponse(responseCode = "201", description = "Session created; creator becomes admin", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = SessionGetDTO.class))
                    }),
                    @ApiResponse(responseCode = "401", description = "Unauthorized")
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/sessions",
            produces = {"application/json"},
            consumes = {"application/json"}
    )

    default ResponseEntity<SessionGetDTO> sessionsPost(
            @Parameter(name = "SessionPostDTO", description = "", required = true) @Valid @RequestBody SessionPostDTO sessionPostDTO
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    /**
     * GET /sessions/{sessionId} : Get session details
     *
     * @param sessionId (required)
     * @return Session details (status code 200)
     * or Session not found (status code 404)
     */
    @Operation(
            operationId = "sessionsSessionIdGet",
            summary = "Get session details",
            tags = {"Sessions"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "Session details", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = SessionGetDTO.class))
                    }),
                    @ApiResponse(responseCode = "404", description = "Session not found")
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/sessions/{sessionId}",
            produces = {"application/json"}
    )

    default ResponseEntity<SessionGetDTO> sessionsSessionIdGet(
            @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") Long sessionId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    /**
     * GET /sessions/{sessionId}/participants : List participants of a session
     *
     * @param sessionId (required)
     * @return List of participants (status code 200)
     */
    @Operation(
            operationId = "sessionsSessionIdParticipantsGet",
            summary = "List participants of a session",
            tags = {"Sessions"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "List of participants", content = {
                            @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = UserGetDTO.class)))
                    })
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/sessions/{sessionId}/participants",
            produces = {"application/json"}
    )

    default ResponseEntity<List<UserGetDTO>> sessionsSessionIdParticipantsGet(
            @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") Long sessionId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    /**
     * POST /sessions/{sessionId}/participants : Join a session via game pin (S5)
     *
     * @param sessionId      (required)
     * @param joinSessionDTO (required)
     * @return Joined successfully (status code 200)
     * or Invalid game pin (status code 400)
     * or Session not found (status code 404)
     */
    @Operation(
            operationId = "sessionsSessionIdParticipantsPost",
            summary = "Join a session via game pin (S5)",
            tags = {"Sessions"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "Joined successfully", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = SessionGetDTO.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Invalid game pin"),
                    @ApiResponse(responseCode = "404", description = "Session not found")
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/sessions/{sessionId}/participants",
            produces = {"application/json"},
            consumes = {"application/json"}
    )

    default ResponseEntity<SessionGetDTO> sessionsSessionIdParticipantsPost(
            @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") Long sessionId,
            @Parameter(name = "JoinSessionDTO", description = "", required = true) @Valid @RequestBody JoinSessionDTO joinSessionDTO
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    /**
     * PUT /sessions/{sessionId}/participants/{userId} : Leave a session – unassigns user from it (S5)
     * Soft-leave: the user is removed from the active participant list but the session record is preserved (e.g. for session history). The session itself is not deleted. Triggers a WebSocket broadcast on /topic/sessions/{sessionId}/participants.
     *
     * @param sessionId (required)
     * @param userId    (required)
     * @return User unassigned from session successfully (status code 204)
     * or Session or participant not found (status code 404)
     */
    @Operation(
            operationId = "sessionsSessionIdParticipantsUserIdPut",
            summary = "Leave a session – unassigns user from it (S5)",
            description = "Soft-leave: the user is removed from the active participant list but the session record is preserved (e.g. for session history). The session itself is not deleted. Triggers a WebSocket broadcast on /topic/sessions/{sessionId}/participants. ",
            tags = {"Sessions"},
            responses = {
                    @ApiResponse(responseCode = "204", description = "User unassigned from session successfully"),
                    @ApiResponse(responseCode = "404", description = "Session or participant not found")
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.PUT,
            value = "/sessions/{sessionId}/participants/{userId}"
    )

    default ResponseEntity<Void> sessionsSessionIdParticipantsUserIdPut(
            @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") Long sessionId,
            @Parameter(name = "userId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("userId") Long userId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /sessions/{sessionId} : Update session status – start / pause / end (S4)
     * Admin-only. Allowed transitions: CREATED → ACTIVE, ACTIVE → PAUSED, PAUSED → ACTIVE, ACTIVE|PAUSED → ENDED
     *
     * @param sessionId     (required)
     * @param sessionPutDTO (required)
     * @return Session updated (status code 200)
     * or Invalid status transition (status code 400)
     * or Only the admin can change session status (status code 403)
     * or Session not found (status code 404)
     */
    @Operation(
            operationId = "sessionsSessionIdPut",
            summary = "Update session status – start / pause / end (S4)",
            description = "Admin-only. Allowed transitions: CREATED → ACTIVE, ACTIVE → PAUSED, PAUSED → ACTIVE, ACTIVE|PAUSED → ENDED ",
            tags = {"Sessions"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "Session updated", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = SessionGetDTO.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Invalid status transition"),
                    @ApiResponse(responseCode = "403", description = "Only the admin can change session status"),
                    @ApiResponse(responseCode = "404", description = "Session not found")
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.PUT,
            value = "/sessions/{sessionId}",
            produces = {"application/json"},
            consumes = {"application/json"}
    )

    default ResponseEntity<SessionGetDTO> sessionsSessionIdPut(
            @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") Long sessionId,
            @Parameter(name = "SessionPutDTO", description = "", required = true) @Valid @RequestBody SessionPutDTO sessionPutDTO
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    /**
     * GET /sessions/{sessionId}/review : Get post-session review of performed songs (S15)
     *
     * @param sessionId (required)
     * @return List of performed songs (status code 200)
     * or Session not ended yet (status code 403)
     * or Session not found (status code 404)
     */
    @Operation(
            operationId = "sessionsSessionIdReviewGet",
            summary = "Get post-session review of performed songs (S15)",
            tags = {"Sessions"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "List of performed songs", content = {
                            @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = SongGetDTO.class)))
                    }),
                    @ApiResponse(responseCode = "403", description = "Session not ended yet"),
                    @ApiResponse(responseCode = "404", description = "Session not found")
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/sessions/{sessionId}/review",
            produces = {"application/json"}
    )

    default ResponseEntity<List<SongGetDTO>> sessionsSessionIdReviewGet(
            @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") Long sessionId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
