/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ch.uzh.ifi.hase.soprafs26.controller;

import ch.uzh.ifi.hase.soprafs26.rest.dto.SongGetDTO;
import ch.uzh.ifi.hase.soprafs26.rest.dto.SongPostDTO;
import ch.uzh.ifi.hase.soprafs26.rest.dto.SongSearchResultDTO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-03-23T14:36:59.836313+01:00[Europe/Zurich]", comments = "Generator version: 7.7.0")
@Validated
@Tag(name = "Songs", description = "Song search and queue management")
public interface SongsApi {


    /**
     * GET /sessions/{sessionId}/songs/current : Get the currently playing song with lyrics (S8)
     *
     * @param sessionId (required)
     * @return Current song with lyrics (status code 200)
     * or No song currently playing (status code 204)
     * or Session not found (status code 404)
     */
    @Operation(
            operationId = "sessionsSessionIdSongsCurrentGet",
            summary = "Get the currently playing song with lyrics (S8)",
            tags = {"Songs"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "Current song with lyrics", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = SongGetDTO.class))
                    }),
                    @ApiResponse(responseCode = "204", description = "No song currently playing"),
                    @ApiResponse(responseCode = "404", description = "Session not found")
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/sessions/{sessionId}/songs/current",
            produces = {"application/json"}
    )

    default ResponseEntity<SongGetDTO> sessionsSessionIdSongsCurrentGet(
            @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") Long sessionId
    ) {

        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /sessions/{sessionId}/songs : Get the ordered song queue of a session
     *
     * @param sessionId (required)
     * @return Ordered song queue (status code 200)
     */
    @Operation(
            operationId = "sessionsSessionIdSongsGet",
            summary = "Get the ordered song queue of a session",
            tags = {"Songs"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "Ordered song queue", content = {
                            @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = SongGetDTO.class)))
                    })
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/sessions/{sessionId}/songs",
            produces = {"application/json"}
    )

    default ResponseEntity<List<SongGetDTO>> sessionsSessionIdSongsGet(
            @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") Long sessionId
    ) {

        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /sessions/{sessionId}/songs : Add a song to the session queue (S6, S10)
     *
     * @param sessionId   (required)
     * @param songPostDTO (required)
     * @return Song added to queue (status code 201)
     * or Session not found (status code 404)
     * or Lyrics not available for this song (status code 422)
     */
    @Operation(
            operationId = "sessionsSessionIdSongsPost",
            summary = "Add a song to the session queue (S6, S10)",
            tags = {"Songs"},
            responses = {
                    @ApiResponse(responseCode = "201", description = "Song added to queue", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = SongGetDTO.class))
                    }),
                    @ApiResponse(responseCode = "404", description = "Session not found"),
                    @ApiResponse(responseCode = "422", description = "Lyrics not available for this song")
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/sessions/{sessionId}/songs",
            produces = {"application/json"},
            consumes = {"application/json"}
    )

    default ResponseEntity<SongGetDTO> sessionsSessionIdSongsPost(
            @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") Long sessionId,
            @Parameter(name = "SongPostDTO", description = "", required = true) @Valid @RequestBody SongPostDTO songPostDTO
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    /**
     * POST /sessions/{sessionId}/songs/skip : Skip the current song – admin only (S7)
     * Advances the queue to the next song without waiting for the current one to finish. Triggers two WebSocket broadcasts: - /topic/sessions/{sessionId}/currentSong with the new current song - /topic/sessions/{sessionId}/votingRound when a new voting round starts automatically
     *
     * @param sessionId (required)
     * @return Skipped; next song returned (status code 200)
     * or Only admin can skip (status code 403)
     * or Session not found (status code 404)
     */
    @Operation(
            operationId = "sessionsSessionIdSongsSkipPost",
            summary = "Skip the current song – admin only (S7)",
            description = "Advances the queue to the next song without waiting for the current one to finish. Triggers two WebSocket broadcasts: - /topic/sessions/{sessionId}/currentSong with the new current song - /topic/sessions/{sessionId}/votingRound when a new voting round starts automatically ",
            tags = {"Songs"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "Skipped; next song returned", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = SongGetDTO.class))
                    }),
                    @ApiResponse(responseCode = "403", description = "Only admin can skip"),
                    @ApiResponse(responseCode = "404", description = "Session not found")
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/sessions/{sessionId}/songs/skip",
            produces = {"application/json"}
    )

    default ResponseEntity<SongGetDTO> sessionsSessionIdSongsSkipPost(
            @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") Long sessionId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    /**
     * DELETE /sessions/{sessionId}/songs/{songId} : Remove a song from the queue – admin only (S7)
     *
     * @param sessionId (required)
     * @param songId    (required)
     * @return Song removed (status code 204)
     * or Only admin can remove songs (status code 403)
     * or Song or session not found (status code 404)
     */
    @Operation(
            operationId = "sessionsSessionIdSongsSongIdDelete",
            summary = "Remove a song from the queue – admin only (S7)",
            tags = {"Songs"},
            responses = {
                    @ApiResponse(responseCode = "204", description = "Song removed"),
                    @ApiResponse(responseCode = "403", description = "Only admin can remove songs"),
                    @ApiResponse(responseCode = "404", description = "Song or session not found")
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.DELETE,
            value = "/sessions/{sessionId}/songs/{songId}"
    )

    default ResponseEntity<Void> sessionsSessionIdSongsSongIdDelete(
            @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") Long sessionId,
            @Parameter(name = "songId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("songId") Long songId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /sessions/{sessionId}/songs/{songId}/played : Mark a song as played – admin only
     * Sets the &#x60;performed&#x60; flag on the song to true after it has been sung.
     *
     * @param sessionId (required)
     * @param songId    (required)
     * @return Song marked as played (status code 200)
     * or Only admin can mark songs as played (status code 403)
     * or Song or session not found (status code 404)
     */
    @Operation(
            operationId = "sessionsSessionIdSongsSongIdPlayedPut",
            summary = "Mark a song as played – admin only",
            description = "Sets the `performed` flag on the song to true after it has been sung.",
            tags = {"Songs"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "Song marked as played", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = SongGetDTO.class))
                    }),
                    @ApiResponse(responseCode = "403", description = "Only admin can mark songs as played"),
                    @ApiResponse(responseCode = "404", description = "Song or session not found")
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.PUT,
            value = "/sessions/{sessionId}/songs/{songId}/played",
            produces = {"application/json"}
    )

    default ResponseEntity<SongGetDTO> sessionsSessionIdSongsSongIdPlayedPut(
            @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") Long sessionId,
            @Parameter(name = "songId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("songId") Long songId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    /**
     * GET /songs/search : Search songs by title or artist via Genius API (S11)
     *
     * @param query (required)
     * @return Search results (status code 200)
     * or Missing or empty query (status code 400)
     */
    @Operation(
            operationId = "songsSearchGet",
            summary = "Search songs by title or artist via Genius API (S11)",
            tags = {"Songs"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "Search results", content = {
                            @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = SongSearchResultDTO.class)))
                    }),
                    @ApiResponse(responseCode = "400", description = "Missing or empty query")
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/songs/search",
            produces = {"application/json"}
    )

    default ResponseEntity<List<SongSearchResultDTO>> songsSearchGet(
            @NotNull @Parameter(name = "query", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "query", required = true) String query
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
