/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ch.uzh.ifi.hase.soprafs26.controller;

import ch.uzh.ifi.hase.soprafs26.rest.dto.SessionGetDTO;
import ch.uzh.ifi.hase.soprafs26.rest.dto.UserPutDTO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-03-23T14:36:59.836313+01:00[Europe/Zurich]", comments = "Generator version: 7.7.0")
@Validated
@Tag(name = "Users", description = "User management")
public interface UsersApi {

    /**
     * PUT /users/{userId} : Update user – e.g. change password (S2)
     *
     * @param userId     (required)
     * @param userPutDTO (required)
     * @return Updated successfully (status code 204)
     * or Password mismatch or invalid input (status code 400)
     * or Forbidden – can only edit own profile (status code 403)
     * or User not found (status code 404)
     */
    @Operation(
            operationId = "usersUserIdPut",
            summary = "Update user – e.g. change password (S2)",
            tags = {"Users"},
            responses = {
                    @ApiResponse(responseCode = "204", description = "Updated successfully"),
                    @ApiResponse(responseCode = "400", description = "Password mismatch or invalid input"),
                    @ApiResponse(responseCode = "403", description = "Forbidden – can only edit own profile"),
                    @ApiResponse(responseCode = "404", description = "User not found")
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.PUT,
            value = "/users/{userId}",
            consumes = {"application/json"}
    )

    default ResponseEntity<Void> usersUserIdPut(
            @Parameter(name = "userId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("userId") Long userId,
            @Parameter(name = "UserPutDTO", description = "", required = true) @Valid @RequestBody UserPutDTO userPutDTO
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /users/{userId}/sessions : Get session history for a user (S13)
     *
     * @param userId (required)
     * @return List of sessions created or joined by user (status code 200)
     * or User not found (status code 404)
     */
    @Operation(
            operationId = "usersUserIdSessionsGet",
            summary = "Get session history for a user (S13)",
            tags = {"Users"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "List of sessions created or joined by user", content = {
                            @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = SessionGetDTO.class)))
                    }),
                    @ApiResponse(responseCode = "404", description = "User not found")
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/users/{userId}/sessions",
            produces = {"application/json"}
    )

    default ResponseEntity<List<SessionGetDTO>> usersUserIdSessionsGet(
            @Parameter(name = "userId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("userId") Long userId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
