/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ch.uzh.ifi.hase.soprafs26.controller;

import ch.uzh.ifi.hase.soprafs26.rest.dto.VotePostDTO;
import ch.uzh.ifi.hase.soprafs26.rest.dto.VotingRoundGetDTO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-03-23T14:36:59.836313+01:00[Europe/Zurich]", comments = "Generator version: 7.7.0")
@Validated
@Tag(name = "Voting", description = "VotingRounds and Votes")
public interface VotingApi {

    /**
     * GET /sessions/{sessionId}/votingRounds : List all voting rounds of a session
     * VotingRounds are started automatically by the server when a song ends.
     *
     * @param sessionId (required)
     * @return List of voting rounds (status code 200)
     */
    @Operation(
            operationId = "sessionsSessionIdVotingRoundsGet",
            summary = "List all voting rounds of a session",
            description = "VotingRounds are started automatically by the server when a song ends.",
            tags = {"Voting"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "List of voting rounds", content = {
                            @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = VotingRoundGetDTO.class)))
                    })
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/sessions/{sessionId}/votingRounds",
            produces = {"application/json"}
    )

    default ResponseEntity<List<VotingRoundGetDTO>> sessionsSessionIdVotingRoundsGet(
            @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") Long sessionId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    /**
     * GET /sessions/{sessionId}/votingRounds/{roundId} : Get a specific voting round – leaderboard (S14)
     *
     * @param sessionId (required)
     * @param roundId   (required)
     * @return Voting round with candidates sorted by vote count (status code 200)
     * or Not found (status code 404)
     */
    @Operation(
            operationId = "sessionsSessionIdVotingRoundsRoundIdGet",
            summary = "Get a specific voting round – leaderboard (S14)",
            tags = {"Voting"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "Voting round with candidates sorted by vote count", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = VotingRoundGetDTO.class))
                    }),
                    @ApiResponse(responseCode = "404", description = "Not found")
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/sessions/{sessionId}/votingRounds/{roundId}",
            produces = {"application/json"}
    )

    default ResponseEntity<VotingRoundGetDTO> sessionsSessionIdVotingRoundsRoundIdGet(
            @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") Long sessionId,
            @Parameter(name = "roundId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("roundId") Long roundId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    /**
     * POST /sessions/{sessionId}/votingRounds/{roundId}/votes : Cast a vote for a candidate song (S12)
     *
     * @param sessionId   (required)
     * @param roundId     (required)
     * @param votePostDTO (required)
     * @return Vote cast (status code 201)
     * or Song is not a candidate in this round (status code 400)
     * or User has already voted in this round (status code 409)
     * or Voting round is CLOSED (status code 410)
     */
    @Operation(
            operationId = "sessionsSessionIdVotingRoundsRoundIdVotesPost",
            summary = "Cast a vote for a candidate song (S12)",
            tags = {"Voting"},
            responses = {
                    @ApiResponse(responseCode = "201", description = "Vote cast"),
                    @ApiResponse(responseCode = "400", description = "Song is not a candidate in this round"),
                    @ApiResponse(responseCode = "409", description = "User has already voted in this round"),
                    @ApiResponse(responseCode = "410", description = "Voting round is CLOSED")
            },
            security = {
                    @SecurityRequirement(name = "BearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/sessions/{sessionId}/votingRounds/{roundId}/votes",
            consumes = {"application/json"}
    )

    default ResponseEntity<Void> sessionsSessionIdVotingRoundsRoundIdVotesPost(
            @Parameter(name = "sessionId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("sessionId") Long sessionId,
            @Parameter(name = "roundId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("roundId") Long roundId,
            @Parameter(name = "VotePostDTO", description = "", required = true) @Valid @RequestBody VotePostDTO votePostDTO
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
